spring.application.name=healthystore

spring.datasource.url=jdbc:postgresql://localhost:5432/healthy_store_db
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
stripe.secret.key=YOUR_STRIPE_SECRET_KEY

server.port=8080